# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=256)),
                ('sector', models.CharField(choices=[('Autotechniek', 'Autotechniek'), ('Bouw', 'Bouw'), ('CIOS', 'CIOS'), ('Dans en Theater', 'Dans en Theater'), ('Entree', 'Entree'), ('Handel en Commercie', 'Handel en Commercie'), ('Horeca en Facility', 'Horeca en Facility'), ('ICT', 'ICT'), ('Lab', 'Lab'), ('Logistiek', 'Logistiek'), ('Maritiem', 'Maritiem'), ('Marketing en Media', 'Marketing en Media'), ('MyTec', 'MyTec'), ('Orde en Veiligheid', 'Orde en Veiligheid'), ('Recreatie', 'Recreatie'), ('Techniek', 'Techniek'), ('Uiterlijke Verzorging', 'Uiterlijke Verzorging'), ('Welzijn', 'Welzijn'), ('Zakelijk', 'Zakelijk'), ('Zorg', 'Zorg')], max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('signature', models.ImageField(upload_to='')),
            ],
        ),
    ]
