# Generated by Django 2.0 on 2018-01-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
